### ISSUE TITLE
Considering send data 

### ISSUE THREAD

**Issue by yousefmlotfy656** [sebmillet/rf433send#1]
i didnt find a way to send data that I received from the 433any library (27 b7 3a bd d9 8b fb bd ff) this is sample of data that I received so how can transmit it again?

**Comment by sebmillet** [comment]
Hello

You can use the output of main.ino example in RF433any lib (https://github.com/sebmillet/RF433any/blob/main/examples/01_main/01_main.ino) to build the corresponding sender object.
It'll require some adjustments (RF433any output is meant to be used as is in RF433recv) though.

You have to look at the example of RF433send to see what is a bit different.
Some parameters are different between the call to rf.register_Receiver and the call to rfsend_builder, since they don't need exactly the same information to do their job.

Also to identify the encoding they follow different naming rules.
RF433recv lib uses the names RFMOD_TRIBIT, RFMOD_TRIBIT_INVERTED, RFMOD_MANCHESTER.
Whereas the RF433send uses the names RfSendEncoding::TRIBIT, RfSendEncoding::TRIBIT_INVERTED, RfSendEncoding::MANCHESTER.

Besides, the same timing parameters logic is employed and both are close.

If you send me the output of RF433any I can show you what call to rfsend_builder to do, and how to send a particular code.

Regards, Sébastien Millet

**Comment by yousefmlotfy656** [comment]
i would like to thank you for being helpful 
considering RF433any output 

Data: 71 0e 5a 23 d9 8b fb bd ff

-----CODE START-----
// [WRITE THE DEVICE NAME HERE]
rf.register_Receiver(
	RFMOD_TRIBIT, // mod
	4000, // initseq
	0, // lo_prefix
	0, // hi_prefix
	0, // first_lo_ign
	420, // lo_short
	794, // lo_long
	0, // hi_short (0 => take lo_short)
	0, // hi_long  (0 => take lo_long)
	772, // lo_last
	4000, // sep
	71  // nb_bits
);
-----CODE END-----
Regards, YousefMLotfy

**Comment by yousefmlotfy656** [comment]
hello Sebmillet,
i tried to send the received signal by converting the received hexadecimal to deciaml and send it using rc switch library but rcswitch library cant send the 71 or 67 bits continuously, i can send only the first half of the signal or the second half so what can i do to send the full signal (71 bits (x1): 07 fd 65 a4 d9 8b fb bd ff ) 

thanks alot

**Comment by yousefmlotfy656** [comment]
actually, I did another trial using your rf433send library and it works with 32 bits but I faced the problem the same problem of the rcswitch that it didn't send more than 32 bits when I tried to send 71 it didn't send it, so please help me to send this bits completely

thanks alot

**Comment by yousefmlotfy656** [comment]
hello can you help!!!

**Comment by yousefmlotfy656** [comment]
Please answer my reply

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
